multipart:
  maxFileSize: 50MB
  maxRequestSize: 50MB
  location: ${java.io.tmpdir}
debug: true
spring:
  mvc:
    favicon:
      enabled: false
com:
  justgifit:
    gif-location: ${java.io.tmpdir}/gif
    optimize: true